# Generated by Django 2.0.6 on 2018-06-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='id',
            fields=[
                ('p_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('userID', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='parkinglotInfo',
            fields=[
                ('parkinglotID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('locationCode', models.IntegerField()),
                ('totalSpace', models.IntegerField()),
                ('currentSpace', models.IntegerField()),
                ('isFree', models.IntegerField()),
                ('note', models.CharField(max_length=45)),
            ],
        ),
    ]
