# Generated by Django 2.0.6 on 2018-06-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0002_auto_20180609_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id',
            name='p_ID',
        ),
        migrations.AlterField(
            model_name='id',
            name='userID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
