# Generated by Django 2.0.6 on 2018-06-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_auto_20180609_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='pID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='parkinglot.parkinglotInfo'),
        ),
    ]
