# Generated by Django 2.0.6 on 2018-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0006_auto_20180609_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglotinfo',
            name='note',
            field=models.CharField(max_length=200),
        ),
    ]
